name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Use a versão mais recente disponível
        with:
          node-version: 16

      # Restante das etapas...


      - name: Install Dependencies and Build
        run: |
          yarn install --frozen-lockfile
          yarn build:action

      - name: Run Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Rafael-Lee1
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
